#! /usr/bin/env perl


################################################################################
#
# runCreateConfig
# ---------------
#
#             09/18/2008 Philipp Schieferdecker <philipp.schieferdecker@cern.ch>
################################################################################


my $dbHost;
my $dbName;
my $dbUser;
my $dbPwrd;

my $masterName;
my $pathList;
my $newName;

my $cmd = 
    "java " .
    "-cp ../ext/ojdbc14.jar:../lib/cmssw-evf-confdb-gui.jar " .
    "confdb.db.ConfDBCreateConfig ";



while (@ARGV)
{
    my $arg = shift @ARGV;
    if ($arg eq "--hltdev")
    {
	$dbHost = "cmsr1-v.cern.ch";
	$dbName = "cms_cond.cern.ch";
	$dbUser = "cms_hltdev_writer";
    }
    elsif ($arg eq "--rcms")
    {
	$dbHost = "cmsonr1-v.cms";
	$dbName = "cms_rcms.cern.ch";
	$dbUser = "cms_hlt_w";
    }
    elsif ($arg eq "--rcms_ssh")
    {
	$dbHost = "localhost";
	$dbName = "cms_rcms.cern.ch";
	$dbUser = "cms_hlt_w";
    }
    elsif ($arg eq "--int2r")
    {
	$dbHost = "int2r1-v.cern.ch";
	$dbName = "int2r_nolb.cern.ch";
	$dbUser = "cms_hlt_writer";
    }
    elsif ($arg eq "--int9r")
    {
	$dbHost = "int9r1-v.cern.ch";
	$dbName = "int9r_nolb.cern.ch";
	$dbUser = "cms_hlt_writer";
    }
    elsif ($arg eq "--dbpwrd") { $dbPwrd     = shift @ARGV; }
    elsif ($arg eq "--master") { $masterName = shift @ARGV; }
    elsif ($arg eq "--paths")  { $pathList   = shift @ARGV; }
    elsif ($arg eq "--name")   { $newName    = shift @ARGV; }
}

die "no db specified (--hltdev / --rcms / --rcms_ssh)" if ($dbHost eq "");
die "no password specified (--dbpwrd)"                 if ($dbPwrd eq "");
die "no master specified (--master)"                   if ($masterName eq "");
die "no path-list specified (--paths)"                 if ($pathList eq "");
die "no name specified (--name)"                       if ($newName eq "");

$cmd = $cmd .
    "-h $dbHost -d $dbName -u $dbUser -s $dbPwrd " .
    "-m $masterName --paths $pathList -n $newName";
    
print $cmd . "\n";
system($cmd);

