#! /usr/bin/env perl


################################################################################
#
# runOfflineConverter
# ------------------
#
#             07/24/2008 Philipp Schieferdecker <philipp.schieferdecker@cern.ch>
################################################################################

my $db_host = "";
my $db_name = "";
my $db_user = "";
my $db_pwrd = "";
my $args    = "";

if (@ARGV==0) {
    print "provide one of: --hltdev, --orcoff, --rcms, --int2r, --int9r, or --test2r!\n";
    exit(0);
}

while (@ARGV)
{
    my $arg = shift @ARGV;
    if ($arg eq "--hltdev") {
	$db_host = "cmsr1-s.cern.ch";
	$db_name = "cms_cond.cern.ch";
	$db_user = "cms_hltdev_reader";
	$db_pwrd = "convertme!";
    }
    elsif ($arg eq "--orcoff") {
	$db_host = "cmsr1-s.cern.ch";
	$db_name = "cms_cond.cern.ch";
	$db_user = "cms_hlt_gui_r";
	$db_pwrd = "convertme!";
    }
    elsif ($arg eq "--rcms") {
	$db_host = "cmsonr1-v.cms";
	$db_name = "cms_rcms.cern.ch";
	$db_user = "cms_hlt_r";
	$db_pwrd = "convertme!";
    }
    elsif ($arg eq "--rcms_tunnel") {
	$db_host = "localhost";
	$db_name = "cms_omds_tunnel.cern.ch";
	$db_user = "cms_hlt_r";
	$db_pwrd = "convertme!";
    }
    elsif ($arg eq "--int2r") {
	$db_host = "int2r1-v.cern.ch";
	$db_name = "int2r_nolb.cern.ch";
	$db_user = "cms_hlt_reader";
	$db_pwrd = "convertme!";
    }
    elsif ($arg eq "--int9r") {
	$db_host = "int9r1-v.cern.ch";
	$db_name = "int9r_nolb.cern.ch";
	$db_user = "cms_hlt_reader";
	$db_pwrd = "convertme!";
    }
    elsif ($arg eq "--test2r") {
	$db_host = "int2r1-s.cern.ch";
	$db_name = "int2r_nolb.cern.ch";
	$db_user = "cms_hltdev";
	$db_pwrd = "Magnum2Classic";
    }
    else { $args = $args . " " . $arg; }
}

my $cmd = 
    "java " .
    "-cp ../ext/ojdbc14.jar:../lib/cmssw-evf-confdb-converter.jar " .
    "confdb.converter.OfflineConverter " .
    "-t oracle -h $db_host -d $db_name -u $db_user -s $db_pwrd $args";


print $cmd . "\n";
system($cmd);

