#! /usr/bin/perl


################################################################################
#
# runPythonParser
# ---------------
#
# 07/24/2008 Philipp Schieferdecker <philipp.schieferdecker@cern.ch>
################################################################################


my $cmd = 
    "java " .
    "-cp ext/ojdbc14.jar:lib/cmssw-evf-confdb-gui.jar " .
    "confdb.parser.PythonParser ";

while (@ARGV)
{
    my $arg = shift @ARGV;
    $cmd = $cmd . " " . $arg; 
}

print $cmd . "\n";
system($cmd);

