#! /bin/bash
BASE=$(dirname $0)

# enable GTK look and feel
#SWING=-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
#SWING="-Dswing.plaf.metal.controlFont=Dialog-20"
SWING=

# enable profiling
#PROFILE=-Xrunhprof:heap=sites,cpu=samples,depth=10
PROFILE=

ant -f $BASE/build.xml gui && java -Doracle.jdbc.timezoneAsRegion=false -Dswing.aatext=true $SWING $PROFILE -classpath $BASE/lib/cmssw-evf-confdb-gui.jar:$BASE/lib/cmssw-python.jar:$BASE/ext/ojdbc6.jar:$BASE/ext/jython.jar confdb.gui.ConfDbGUI
