package confdb.gui;

import java.util.Iterator;

import javax.swing.DefaultComboBoxModel;

import confdb.data.Configuration;
import confdb.data.Stream;
import confdb.data.PrimaryDataset;


/**
 * CreateDatasetDialog
 * -------------------
 * @author Philipp Schieferdecker
 *
 * Create a new primary dataset off an existing stream.
 */
public class CreateDatasetDialog extends javax.swing.JPanel
{
    //
    // member data
    //

    /** reference to the configuration */
    private Configuration config = null;

    /** created dataset */
    private PrimaryDataset dataset = null;

    //
    // construction
    //

    /** Creates new form CreateDatasetDialog */
    public CreateDatasetDialog(Configuration config)
    {
        this.config = config;
        initComponents();
        updateStreamList();
    }


    //
    // public member functions
    //

    /** indicate wether dataset was successfully created */
    public boolean isSuccess() { return dataset!=null; }

    /** retrieve the created primary dataset */
    public PrimaryDataset dataset() { return dataset; }


    //
    // private member functions
    //

    /** update combo box with list of streams */
    private void updateStreamList()
    {
        DefaultComboBoxModel cbm =
    (DefaultComboBoxModel)jComboBoxStreamLabel.getModel();
        cbm.removeAllElements();
        Iterator<Stream> itS = config.streamIterator();
        while (itS.hasNext()) {
            Stream stream = itS.next();
            cbm.addElement(stream.label());
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldDatasetLabel = new javax.swing.JTextField();
        jComboBoxStreamLabel = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        jLabel1.setText("Primary Dataset Name:");

        jTextFieldDatasetLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDatasetLabelActionPerformed(evt);
            }
        });

        jComboBoxStreamLabel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Stream:");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDatasetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxStreamLabel, 0, 350, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(258, 258, 258)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOK)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonOK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDatasetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxStreamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDatasetLabelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldDatasetLabelActionPerformed
    {//GEN-HEADEREND:event_jTextFieldDatasetLabelActionPerformed
        String datasetLabel = jTextFieldDatasetLabel.getText();
        if (config.dataset(datasetLabel)==null) jButtonOK.setEnabled(true);
        else jButtonOK.setEnabled(false);
    }//GEN-LAST:event_jTextFieldDatasetLabelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOKActionPerformed
    {//GEN-HEADEREND:event_jButtonOKActionPerformed
        String datasetLabel = jTextFieldDatasetLabel.getText();
        String streamLabel  = (String)jComboBoxStreamLabel.getSelectedItem();
        Stream stream = config.stream(streamLabel);
        dataset = stream.insertDataset(datasetLabel);
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxStreamLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldDatasetLabel;

    boolean isSuccess()
    {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    // End of variables declaration//GEN-END:variables

}
