--
-- ADD 'CASCADE ON DELETE' FK CONSTRAINTS ON CMS_RCMS (!!)
--

ALTER TABLE EDSourceTemplates DROP CONSTRAINT SYS_C0036894;
ALTER TABLE ESSourceTemplates DROP CONSTRAINT SYS_C0036911;
ALTER TABLE ESModuleTemplates DROP CONSTRAINT SYS_C0036930;
ALTER TABLE ServiceTemplates  DROP CONSTRAINT SYS_C0036877;
ALTER TABLE ModuleTemplates   DROP CONSTRAINT SYS_C0036953;

@add_CoD.sql
