--
-- ADD 'CASCADE ON DELETE' FK CONSTRAINTS ON CMS_ORCOFF_INT (INT9R!!)
--

ALTER TABLE EDSourceTemplates DROP CONSTRAINT SYS_C0069913;
ALTER TABLE ESSourceTemplates DROP CONSTRAINT SYS_C0069930;
ALTER TABLE ESModuleTemplates DROP CONSTRAINT SYS_C0069949;
ALTER TABLE ServiceTemplates  DROP CONSTRAINT SYS_C0069896;
ALTER TABLE ModuleTemplates   DROP CONSTRAINT SYS_C0069972;

@add_CoD.sql
