COLUMN NAME FORMAT A32;
COLUMN VALUE FORMAT A32;

SELECT
  PATHS.NAME,
  STRINGPARAMVALUES.VALUE
FROM
  STRINGPARAMVALUES
JOIN
  PARAMETERS ON PARAMETERS.PARAMID = STRINGPARAMVALUES.PARAMID
JOIN
  SUPERIDPARAMETERASSOC ON SUPERIDPARAMETERASSOC.PARAMID = PARAMETERS.PARAMID
JOIN
  MODULES ON MODULES.SUPERID = SUPERIDPARAMETERASSOC.SUPERID
JOIN
  MODULETEMPLATES ON MODULETEMPLATES.SUPERID = MODULES.TEMPLATEID
JOIN
  PATHMODULEASSOC ON PATHMODULEASSOC.MODULEID = MODULES.SUPERID
JOIN
  PATHS ON PATHS.PATHID = PATHMODULEASSOC.PATHID
JOIN
  CONFIGURATIONPATHASSOC ON CONFIGURATIONPATHASSOC.PATHID = PATHS.PATHID
JOIN
  CONFIGURATIONS ON CONFIGURATIONS.CONFIGID = CONFIGURATIONPATHASSOC.CONFIGID
WHERE
  MODULETEMPLATES.NAME = 'HLTLevel1GTSeed' AND
  PARAMETERS.NAME = 'L1SeedsLogicalExpression' AND
  CONFIGURATIONS.CONFIGDESCRIPTOR = '&1' AND
  PATHS.NAME ='&2';
  