COLUMN CONSTRAINT_NAME FORMAT A24;
COLUMN TABLE_NAME      FORMAT A24;
COLUMN COLUMN_NAME     FORMAT A24;

SELECT a.CONSTRAINT_NAME,a.CONSTRAINT_TYPE,a.TABLE_NAME,b.COLUMN_NAME
FROM USER_CONSTRAINTS a JOIN USER_CONS_COLUMNS b
ON b.CONSTRAINT_NAME=a.CONSTRAINT_NAME
WHERE a.CONSTRAINT_TYPE='R' AND b.COLUMN_NAME='SUPERID'
AND (a.TABLE_NAME='EDSOURCETEMPLATES' OR
     a.TABLE_NAME='ESSOURCETEMPLATES' OR
     a.TABLE_NAME='ESMODULETEMPLATES' OR
     a.TABLE_NAME='SERVICETEMPLATES'  OR
     a.TABLE_NAME='MODULETEMPLATES');
