sqlplus CMS_HLT_TEST@CMS_ORCOFF_INT2R/hltdevtest1 < hlt_drop_db_ORACLE.sql
sqlplus CMS_HLT_TEST@CMS_ORCOFF_INT2R/hltdevtest1 < hlt_create_db_ORACLE.sql
sqlplus CMS_HLT_TEST@CMS_ORCOFF_INT2R/hltdevtest1 < hlt_create_synonyms_ORACLE.sql
sqlplus CMS_HLT_TEST@CMS_ORCOFF_INT2R/hltdevtest1 < hlt_create_procedures_ORACLE.sql
